### ISSUE TITLE
Cannot initialize PrivateKey object from string

### ISSUE THREAD

**Issue by dbrkic-symphony** [hashgraph/hedera-sdk-swift#27]
### Description

Cannot initialise private key from PrivateKey constructor when passing private key from string created using Hashpack or Blade Wallet. 

However, it's working fine when using private key that has been generated using PrivateKey generate methods.

### Steps to reproduce

1. Create a testnet wallet using Hashpack or Blade Wallet
2. Reveal the wallet private key
3. Use the wallet private key string in PrivateKey(stringLiteral:) constructor

### Additional context

Using my testnet private key: 
`let pkString = "302e..."`
`let pkInstance = PrivateKey(stringLiteral: pkString)`
The application throws an exception in PrivateKey.swift file at line 25:
`if err != HEDERA_ERROR_OK {
            return nil
        }`
where 
`err = [.HEDERA_ERROR_GRPC_STATUS, .HEDERA_ERROR_QUERY_NO_PAYMENT_PRE_CHECK_STATUS]`

### Hedera network

testnet

### Version

v.0.6.0

### Operating system

macOS

**Comment by skyler-lb** [comment]
Hi! This has been fixed in https://github.com/hashgraph/hedera-sdk-rust/commit/2c388785e369dfcc8d280255d542ab8da047d888 (it was a :bug: in the Rust core, which has now been fixed), and hasn't been released in Swift yet, I'm not sure what needs to be done for a 0.6.1 release (fixing this would not be a breaking change), but I'll definitely check in wrt it.

**Comment by mehcode** [comment]
Fixed in https://github.com/hashgraph/hedera-sdk-swift/releases/tag/0.7.0
