### ISSUE TITLE
Cannot get precheck code for error case

### ISSUE THREAD

**Issue by soharang** [hashgraph/hedera-sdk-swift#42]
### Description

After execute transaction, I cannot get precheck code from HError for error cases.

### Steps to reproduce

Here is an example code with `HederaPrecheckStatusError` but `HederaPrecheckStatusError` is not defined in the sdk yet.
```
do {
    let response = try await TransferTransaction()
        .tokenTransfer(tokenId, accountId1, -10)
        .tokenTransfer(tokenId, accountId2, 10)
        .freezeWith(client)
        .sign(privateKey1)
        .execute(client)
        .getReceipt(client)
} catch let error as HError {
    if let precheckError = error as? HederaPrecheckStatusError { // Cannot use HederaPrecheckStatusError
        // Handle precheck status errors
        let status = precheckError.status
        switch status {
        case .invalidAccountId:
            print("Invalid Account ID")
        case .tokenNotAssociatedToAccount:
            print("Token not associated to account")
        // Add other cases as needed
        default:
            print("Other precheck status error")
        }
    } else {
        // Handle other error cases
        print("Other error: \(error)")
    }
}
```

### Hedera network

mainnet

### Version

0.15.0

### Operating system

macOS

**Comment by mgarbs** [comment]
We may want to tag this an an enhancement

**Comment by soharang** [comment]
@mgarbs Sure. Thanks for your explanation in discord.

**Comment by izik1** [comment]
Hi! Just wanted to let you know that it is absolutely doable, just not in the way you might expect currently

Currently errors are defined as a struct with an enum inside:
https://github.com/hashgraph/hedera-sdk-swift/blob/8f326c2765fe69d66d6c59ce6788551107293054/Sources/Hedera/HError.swift#L108

you can currently `switch`/`if case` on the following cases to perform the expected behavior:
https://github.com/hashgraph/hedera-sdk-swift/blob/8f326c2765fe69d66d6c59ce6788551107293054/Sources/Hedera/HError.swift#L84-L88

Note that this was only added as of 0.15, although that is the version that you wrote down.

**Comment by soharang** [comment]
@izik1 Thank you for your good guide. It worked like a charm 👍 👍
